pull_request_rules:
- name: dependabot-auto-merge
  description: Automatically merge dependabot PRs that pass CI
  conditions:
    - author=dependabot[bot]
    - check-success=golangci-lint-worker
    - check-success=golangci-lint-bot
    - check-success=ansible
    - check-success=Shellcheck
    - check-success=markdown-lint
    - check-success=DCO
    - label!=hold
  actions:
    merge:
      method: merge

- name: auto-merge
  description: automatic merge for main with > 1 approved reviews, all requested reviews have given feedback, not held, and CI is successful
  conditions:
    - "#approved-reviews-by>=1"
    - "#review-requested=0"
    - "#changes-requested-reviews-by=0"
    - base=main
    - label!=hold
    - check-success=golangci-lint-worker
    - check-success=golangci-lint-bot
    - check-success=ansible
    - check-success=Shellcheck
    - check-success=markdown-lint
    - check-success=DCO
    # If files are changed in .github/, the actionlint check must pass
    - or:
      - and:
        # regex should match the one in .github/workflows/actionlint.yml
        - files~=.github/.*$
        - check-success=actionlint
      - -files~=.github/.*$
  actions:
    merge:
      method: merge
